spring:
  datasource:
    username: root
    password: hufei169357
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#指定myBatis的核心配置文件与Mapper映射文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 注意：对应实体类的路径
  type-aliases-package: com.feige.pojo

  mvc:
    favicon:
      enabled: false

  #禁用模板缓存
  thymeleaf:
    cache: false